stock_project/admin_panel/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('categories/', views.liste_categories, name='liste_categories'),
    path('fournisseurs/', views.liste_fournisseurs, name='liste_fournisseurs'),
    path('ajouter-fournisseur/', views.ajouter_fournisseur, name='ajouter_fournisseur'),
    path('supprimer-fournisseur/<int:fournisseur_id>/', views.supprimer_fournisseur, name='supprimer_fournisseur'),
    path('ajouter-categorie/', views.ajouter_categorie, name='ajouter_categorie'),
    path('supprimer-categorie/<int:categorie_id>/', views.supprimer_categorie, name='supprimer_categorie'),
    path('ajouter-produit/', views.ajouter_produit, name='ajouter_produit'),
    path('detail-produit/<int:produit_id>/', views.detail_produit, name='detail_produit'),
    path('liste-produits/', views.liste_produits, name='liste_produits'),
    path('supprimer-produit/<int:produit_id>/', views.supprimer_produit, name='supprimer_produit'),
    path('modifier-produit/<int:produit_id>/', views.modifier_produit, name='modifier_produit'),
    path('gerer-stock/', views.gerer_stock, name='gerer_stock'),
    path('reapprovisionnement-stock/', views.reapprovisionnement_stock, name='reapprovisionnement_stock'),
    path('historique-approvisionnement/', views.historique_approvisionnement, name='historique_approvisionnement'),

]


stock_project/employe_panel/urls.py
from django.urls import path
from . import views
app_name = 'employe_panel' 
urlpatterns = [
    path('dashboard/', views.employe_dashboard, name='employe_dashboard'),
    path('inscription-client/', views.inscription_client, name='inscription_client'),
    path('ajouter-commande/', views.ajouter_commande, name='ajouter_commande'),
    path('command-history/', views.command_history, name='command_history'),
    path('sales-trends/', views.sales_trends, name='sales_trends'),
    path('imprimer-facture/<int:commande_id>/', views.imprimer_facture, name='imprimer_facture'),


]

stock_project/stock_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('custom_auth.urls')),
    path('admin-panel/', include('admin_panel.urls')),
    path('employe-panel/', include('employe_panel.urls')),

]

stock_project/employe_panel/models.py
# models.py
from django.db import models

from admin_panel.models import Produit

class Client(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    telephone = models.CharField(max_length=15)
    adresse = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.prenom} {self.nom}"


class Commande(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    date = models.DateField()
    quantite = models.IntegerField()

    def __str__(self):
        return f"Commande {self.id} - {self.client.nom} - {self.produit.nom}"
    


class Facture(models.Model):
    commande = models.OneToOneField(Commande, on_delete=models.CASCADE)
    contenu_html = models.TextField()

stock_project/employe_panel/forms.py
# forms.py
from django import forms
from .models import Client
from .models import Commande

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['nom', 'prenom', 'email', 'telephone', 'adresse']





class CommandeForm(forms.ModelForm):
    class Meta:
        model = Commande
        fields = ['client', 'produit', 'date', 'quantite']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

    def clean_quantite(self):
        quantite = self.cleaned_data['quantite']
        produit = self.cleaned_data['produit']
        if quantite > produit.quantite:
            raise forms.ValidationError("La quantité demandée est supérieure à la quantité disponible.")
        return quantite

stock_project/employe_panel/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Commande
from collections import Counter
from django.db.models import Sum  
from .forms import CommandeForm
from .forms import ClientForm
from django.template.loader import get_template
from xhtml2pdf import pisa
from .models import Facture


def employe_dashboard(request):
    return render(request, 'employe_panel/dashboard.html')



def inscription_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('employe_panel:ajouter_commande') 
    else:
        form = ClientForm()
    return render(request, 'employe_panel/inscription_client.html', {'form': form})



def ajouter_commande(request):
    if request.method == 'POST':
        form = CommandeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('employe_panel:command_history')  
    else:
        form = CommandeForm()
    return render(request, 'employe_panel/ajouter_commande.html', {'form': form})


def command_history(request):
    commandes = Commande.objects.all()
    return render(request, 'employe_panel/command_history.html', {'commandes': commandes})




def sales_trends(request):
    commandes = Commande.objects.all()
    
    product_sales = Counter()
    for commande in commandes:
        product_sales[commande.produit.nom] += commande.quantite
    
    sorted_products = sorted(product_sales.items(), key=lambda x: x[1], reverse=True)
    
    return render(request, 'employe_panel/sales_trends.html', {'product_sales': sorted_products})


def imprimer_facture(request, commande_id):
    commande = Commande.objects.get(pk=commande_id)
    template_path = 'employe_panel/facture_template.html'
    context = {'commande': commande}
    template = get_template(template_path)
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="facture.pdf"'
    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse('Une erreur s\'est produite lors de la génération du PDF')
    else:
        facture = Facture(commande=commande, contenu_html=html)
        facture.save()
        return response

stock_project/employe_panel/templates/employe_panel/ajouter_commande.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter Commande</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
        }

        .container {
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .dashboard-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 1px solid #ccc;
        }

        .dashboard-header h1 {
            margin: 0;
            color: #333;
        }

        .dashboard-header a {
            text-decoration: none;
            color: #555;
            margin-left: 10px;
        }

        h1 {
            text-align: center;
            margin-top: 20px;
        }

        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        th,
        td {
            padding: 12px 15px;
            border-bottom: 1px solid #ddd;
            text-align: left;
        }

        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #e0e0e0;
        }


        button[type="submit"] {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        input[type="text"],
        input[type="number"],
        input[type="date"],
        select {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="dashboard-header">
            <h1>Liste des catégories</h1>
            <div>
                <a href="{% url 'admin_dashboard' %}">Retour</a>



            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Ajouter Commande</button>
        </form>
    </div>
</body>

</html>

stock_project/employe_panel/templates/employe_panel/command_history.html
<!-- command_history.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Command History</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
        }
    
        .container {
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    
        .dashboard-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 1px solid #ccc;
        }
    
        .dashboard-header h1 {
            margin: 0;
            color: #333;
        }
    
        .dashboard-header a {
            text-decoration: none;
            color: #555;
            margin-left: 10px;
        }
    
        h1 {
            text-align: center;
            margin-top: 20px;
        }
    
        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    
        th,
        td {
            padding: 12px 15px;
            border-bottom: 1px solid #ddd;
            text-align: left;
        }
    
        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }
    
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    
        tr:hover {
            background-color: #e0e0e0;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="dashboard-header">
            <h1>Commande Historique</h1>
            <div>        
            </div>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Client</th>
                    <th>Produit</th>
                    <th>Date</th>
                    <th>Quantité</th>
                    <th>Imprimer Facture</th>
                </tr>
            </thead>
            <tbody>
                {% for commande in commandes %}
                <tr>
                    <td>{{ commande.client }}</td>
                    <td>{{ commande.produit }}</td>
                    <td>{{ commande.date }}</td>
                    <td>{{ commande.quantite }}</td>
                    <td>
                        <a href="{% url 'employe_panel:imprimer_facture' commande_id=commande.id %}" target="_blank">Imprimer</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

stock_project/employe_panel/templates/employe_panel/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
        }

        button[type="submit"] {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }

        .container {
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .dashboard-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 1px solid #ccc;
        }

        .dashboard-header h1 {
            margin: 0;
            color: #333;
        }

        .dashboard-header a {
            text-decoration: none;
            color: #555;
            margin-left: 10px;
        }

        .dashboard-sections {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }

        .dashboard-section {
            flex: 1 1 45%;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-bottom: 20px;
        }

        .dashboard-section h2 {
            margin-top: 0;
            color: #333;
        }

        .dashboard-section ul {
            padding: 0;
            list-style: none;
        }

        .dashboard-section ul li {
            margin-bottom: 10px;
        }

        .dashboard-section ul li a {
            text-decoration: none;
            color: #555;
            display: flex;
            align-items: center;
        }

        .dashboard-section ul li a:hover {
            color: #007bff;
        }

        .dashboard-section ul li a i {
            margin-right: 10px;
            color: #007bff;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="dashboard-header">
            <h1>Welcome to Employe Dashboard, {{ admin_name }}</h1>
            <div>
               
                <form action="{% url 'logout' %}" method="post" id="logout-form">
                    {% csrf_token %}
                    <button type="submit"><i class="fas fa-sign-out-alt"></i> Logout</button>
                </form>

            </div>
        </div>
        <div class="dashboard-sections">


            <div class="dashboard-section">
                <h2>Consulter l'historique des commandes</h2>
                <ul>
                    <li><a href="{% url 'employe_panel:inscription_client'%}"><i class="fas fa-list-alt"></i> Inscrire un client</a></li>
                    <li><a href="{% url 'employe_panel:ajouter_commande'%}"><i class="fas fa-list-alt"></i> Ajouter une commande</a></li>
                    <li><a href="{% url 'employe_panel:command_history'%}"><i class="fas fa-list-alt"></i> Voir le suivi des commandes</a></li>
                    <li><a href="{% url 'employe_panel:sales_trends'%}"><i class="fas fa-list-alt"></i> Tendences des ventes</a></li>
                </ul>
            </div>
        </div>
    </div>
</body>

</html>

stock_project/employe_panel/templates/employe_panel/facture_template.html
<!-- facture_template.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facture</title>
    <style>
        /* Styles CSS pour la facture */
    </style>
</head>

<body>
    <h1>Facture</h1>
    <table>
        <thead>
            <tr>
                <th>Client</th>
                <th>Produit</th>
                <th>Date</th>
                <th>Quantité</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ commande.client }}</td>
                <td>{{ commande.produit }}</td>
                <td>{{ commande.date }}</td>
                <td>{{ commande.quantite }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>

stock_project/employe_panel/templates/employe_panel/inscription_client.html
<!-- inscription_client.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription Client</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
        }
    
        .container {
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    
        .dashboard-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 1px solid #ccc;
        }
    
        .dashboard-header h1 {
            margin: 0;
            color: #333;
        }
    
        .dashboard-header a {
            text-decoration: none;
            color: #555;
            margin-left: 10px;
        }
    
        h1 {
            text-align: center;
            margin-top: 20px;
        }
    
        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    
        th,
        td {
            padding: 12px 15px;
            border-bottom: 1px solid #ddd;
            text-align: left;
        }
    
        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }
    
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    
        tr:hover {
            background-color: #e0e0e0;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }

        button[type="submit"] {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
        }
        input[type="text"],
        input[type="email"],
        select {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="dashboard-header">
            <h1>Inscription Client</h1>
        
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">S'inscrire</button>
        </form>
    </div></div>
</body>

</html>

stock_project/employe_panel/templates/employe_panel/sales_trends.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Trends</title>
    <style>
        body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f8f9fa;
}

.container {
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .dashboard-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 1px solid #ccc;
        }
    
        .dashboard-header h1 {
            margin: 0;
            color: #333;
        }
    
        .dashboard-header a {
            text-decoration: none;
            color: #555;
            margin-left: 10px;
        }

h1 {
    text-align: center;
    margin-top: 20px;
    color: #333;
}

h2 {
    margin-top: 30px;
    color: #333;
}

ul {
    list-style-type: none;
    padding: 0;
}

li {
    margin-bottom: 10px;
    background-color: #fff;
    border-radius: 5px;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    padding: 10px;
}

li:hover {
    background-color: #f2f2f2;
}

    </style>
</head>

<body>
    <div class="container">
        <div class="dashboard-header">
            <h1>Tendence des produit</h1>
            <div>
        
        
        
            </div>
        </div>

        <ul>
            {% for product, sales_quantity in product_sales %}
            <li>{{ product }} - {{ sales_quantity }}</li>
            {% endfor %}
        </ul>

    </div>
</body>

</html>